// <auto-generated />
using System;
using EcoTrails.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcoTrails.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260225171120_SeedInitialTrails")]
    partial class SeedInitialTrails
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EcoTrails.Api.Models.Trail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<double>("DurationInHours")
                        .HasColumnType("float");

                    b.Property<int>("ElevationGain")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Trails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 4, 16, 36, 11, 0, DateTimeKind.Utc),
                            Description = "От Киреево тръгва екопътека, която носи името \"Ерантис Булгарикум\" и извежда до защитена местност \"Връшка чука\".",
                            Difficulty = 3,
                            DurationInHours = 2.5,
                            ElevationGain = 200,
                            Location = "Киреево",
                            Name = "Екопътека \"Ерантис\" – Киреево"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 4, 16, 36, 11, 0, DateTimeKind.Utc),
                            Description = "Трасето на пътеката минава през гориста местност и свързва Етъра и Соколския манастир.",
                            Difficulty = 3,
                            DurationInHours = 2.0,
                            ElevationGain = 120,
                            Location = "Етър",
                            Name = "Екопътека \"Етър-Соколски манастир\""
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 2, 4, 16, 36, 11, 0, DateTimeKind.Utc),
                            Description = "Средно тежък кръгов маршрут с панорамни гледки към Белоградчишките скали и връх Ведерник.",
                            Difficulty = 4,
                            DurationInHours = 4.0,
                            ElevationGain = 450,
                            Location = "Белоградчик",
                            Name = "Екопътека \"Збегове\" – Белоградчик"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
